name: Deploy AWS PROD

on:
  push:
    branches:
      - main
      
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        echo vai gerar a imagem docker
        echo repository name: $AWS_ECR_REPOSITORY_NAME
        echo region: $AWS_REGION

  deploy-prod:
    needs: build-docker-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Deploy PROD
      run: echo "Deploy em PROD"