name: Deploy AWS PROD

on:
  push:
    branches:
      - main

jobs:
  publish-ecr:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  
    - name: Maven Build
      run: mvn clean package
      working-directory: ./

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION}}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: myGitHubActions

    - name: Build Docker Image
      run: |
        docker build -t api-soat .
        docker tag api-soat:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/api-soat:latest

    - name: Push to ECR
      run: docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/api-soat:latest