name: Deploy AWS HOMOLOG

on:
  push:
    branches:
      - release
      
jobs:
  deploy-homolog:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Deploy dev
      run: echo "Deploy em HOMOLOG"
